import React from "react";
import type { IconProps } from "./index";
import {
  XIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ExternalLinkIcon,
  MoreVerticalIcon,
  MaximizeIcon,
  MoveIcon,
  CheckIcon,
  CheckCircleIcon,
  CheckCircle2Icon,
  XCircleIcon,
  AlertCircleIcon,
  AlertTriangleIcon,
  InfoIcon,
  HelpCircleIcon,
  LoaderIcon,
  Loader2Icon,
  FileIcon,
  FileTextIcon,
  FileArchiveIcon,
  FileAudioIcon,
  FileVideoIcon,
  FileQuestionIcon,
  FileUpIcon,
  FileUploadIcon,
  FolderIcon,
  NewFolderIcon,
  UploadFolderIcon,
  FilesIcon,
  SmallFolderIcon,
  ArchiveIcon,
  HardDriveIcon,
  ImageIcon,
  RecycleBinIcon,
  DownloadIcon,
  UploadIcon,
  ShareIcon,
  Share2Icon,
  CopyIcon,
  ClipboardCopyIcon,
  Trash2Icon,
  SaveIcon,
  EditIcon,
  Edit3Icon,
  RefreshCwIcon,
  RotateCcwIcon,
  RotateCwIcon,
  ZoomInIcon,
  ZoomOutIcon,
  PrinterIcon,
  LockIcon,
  UnlockIcon,
  ShieldIcon,
  ShieldCheckIcon,
  EyeIcon,
  EyeOffIcon,
  FingerprintIcon,
  MailIcon,
  SearchIcon,
  PlusIcon,
  SettingsIcon,
  SlidersIcon,
  SlidersHorizontalIcon,
  FilterIcon,
  BellIcon,
  CalendarIcon,
  ClockIcon,
  StarIcon,
  TagIcon,
  HashIcon,
  TypeIcon,
  AlignLeftIcon,
  AlignCenterIcon,
  AlignRightIcon,
  SquareIcon,
  KeyboardIcon,
  MonitorIcon,
  SmartphoneIcon,
  TabletIcon,
  LaptopIcon,
  DevicesIcon,
  MessageSquareIcon,
  SendIcon,
  BotIcon,
  SparklesIcon,
  CornerDownLeftIcon,
  BookOpenIcon,
  CodeIcon,
  TerminalIcon,
  GlobeIcon,
  LinkIcon,
  Link2Icon,
  ZapIcon,
  LayersIcon,
  GithubIcon,
  TwitterIcon,
  YoutubeIcon,
  UserIcon,
  UsersIcon,
  PersonIcon,
  SharedWithYouIcon,
  HomeIcon,
  LogOutIcon,
  NotificationCenterIcon,
  RecentlyEditedIcon,
  HelpCenterIcon,
  WarningIcon,
} from "./index";

const iconMap = {
  // Navigation / UI
  x: XIcon,
  close: XIcon,
  arrowLeft: ArrowLeftIcon,
  arrowRight: ArrowRightIcon,
  chevronDown: ChevronDownIcon,
  chevronLeft: ChevronLeftIcon,
  chevronRight: ChevronRightIcon,
  externalLink: ExternalLinkIcon,
  moreVertical: MoreVerticalIcon,
  maximize: MaximizeIcon,
  maximize2: MaximizeIcon,
  move: MoveIcon,
  // Status / Feedback
  check: CheckIcon,
  checkCircle: CheckCircleIcon,
  checkCircle2: CheckCircle2Icon,
  xCircle: XCircleIcon,
  alertCircle: AlertCircleIcon,
  alertTriangle: AlertTriangleIcon,
  info: InfoIcon,
  helpCircle: HelpCircleIcon,
  loader: LoaderIcon,
  loader2: Loader2Icon,
  // Files
  file: FileIcon,
  fileText: FileTextIcon,
  fileArchive: FileArchiveIcon,
  fileAudio: FileAudioIcon,
  fileVideo: FileVideoIcon,
  fileQuestion: FileQuestionIcon,
  fileUp: FileUpIcon,
  fileUpload: FileUploadIcon,
  folder: FolderIcon,
  newFolder: NewFolderIcon,
  uploadFolder: UploadFolderIcon,
  files: FilesIcon,
  smallFolder: SmallFolderIcon,
  archive: ArchiveIcon,
  hardDrive: HardDriveIcon,
  image: ImageIcon,
  recycleBin: RecycleBinIcon,
  // Actions
  download: DownloadIcon,
  upload: UploadIcon,
  share: ShareIcon,
  share2: Share2Icon,
  copy: CopyIcon,
  clipboardCopy: ClipboardCopyIcon,
  trash2: Trash2Icon,
  save: SaveIcon,
  edit: EditIcon,
  edit3: Edit3Icon,
  refreshCw: RefreshCwIcon,
  rotateCcw: RotateCcwIcon,
  rotateCw: RotateCwIcon,
  zoomIn: ZoomInIcon,
  zoomOut: ZoomOutIcon,
  printer: PrinterIcon,
  // Auth / Security
  lock: LockIcon,
  unlock: UnlockIcon,
  shield: ShieldIcon,
  shieldCheck: ShieldCheckIcon,
  eye: EyeIcon,
  eyeOff: EyeOffIcon,
  fingerprint: FingerprintIcon,
  mail: MailIcon,
  // UI Controls
  search: SearchIcon,
  plus: PlusIcon,
  settings: SettingsIcon,
  sliders: SlidersIcon,
  slidersHorizontal: SlidersHorizontalIcon,
  filter: FilterIcon,
  bell: BellIcon,
  calendar: CalendarIcon,
  clock: ClockIcon,
  star: StarIcon,
  tag: TagIcon,
  hash: HashIcon,
  type: TypeIcon,
  alignLeft: AlignLeftIcon,
  alignCenter: AlignCenterIcon,
  alignRight: AlignRightIcon,
  square: SquareIcon,
  keyboard: KeyboardIcon,
  // Devices
  monitor: MonitorIcon,
  smartphone: SmartphoneIcon,
  tablet: TabletIcon,
  laptop: LaptopIcon,
  devices: DevicesIcon,
  // Communication
  messageSquare: MessageSquareIcon,
  send: SendIcon,
  bot: BotIcon,
  sparkles: SparklesIcon,
  cornerDownLeft: CornerDownLeftIcon,
  // Media / Content
  bookOpen: BookOpenIcon,
  code: CodeIcon,
  terminal: TerminalIcon,
  globe: GlobeIcon,
  link: LinkIcon,
  link2: Link2Icon,
  zap: ZapIcon,
  layers: LayersIcon,
  // Brands
  github: GithubIcon,
  twitter: TwitterIcon,
  youtube: YoutubeIcon,
  // People
  user: UserIcon,
  users: UsersIcon,
  person: PersonIcon,
  sharedWithYou: SharedWithYouIcon,
  // Navigation / branded
  home: HomeIcon,
  logout: LogOutIcon,
  logOut: LogOutIcon,
  notificationCenter: NotificationCenterIcon,
  recentlyEdited: RecentlyEditedIcon,
  helpCenter: HelpCenterIcon,
  warning: WarningIcon,
} as const;

export type IconName = keyof typeof iconMap;

interface Props extends IconProps {
  name: IconName;
}

/**
 * Unified icon component. Pulls all icons from the centralized /icons system.
 *
 * Usage:
 *   <Icon name="search" size={20} className="text-muted-foreground" />
 *   <Icon name="download" size={16} aria-hidden={false} title="Download file" />
 */
const Icon = ({ name, ...props }: Props) => {
  const Comp = iconMap[name];
  if (!Comp) return null;
  return <Comp {...props} />;
};

export default Icon;
